# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('school', 'School'), ('university', 'University'), ('smallbusiness', 'Small Business'), ('largebusiness', 'Large Business'), ('studentteam', 'Students Team'), ('studentteam', 'Students Team'), ('researchinstitute', 'Research Institute'), ('enterprenureship', 'Enterprenureship')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('profilepic', models.ImageField(upload_to='host/profilepics')),
                ('email', models.EmailField(max_length=254)),
                ('instituition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.Institutions')),
            ],
        ),
    ]
