# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='picture',
            field=models.ImageField(default='DataRoot/schools/school/displayPics/defaultavatar.png', upload_to='schools/school/displayPics/'),
        ),
    ]
