# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20160406_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='picture',
            field=models.FileField(upload_to='schools/school/display/'),
        ),
    ]
