# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20160407_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='picture',
        ),
    ]
