# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_school_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='schools/display/'),
        ),
    ]
