# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.User')),
            ],
        ),
        migrations.AddField(
            model_name='stocks',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_stockexchange.Symbols'),
        ),
        migrations.AddField(
            model_name='stocks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_stockexchange.User'),
        ),
        migrations.AddField(
            model_name='history',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_stockexchange.Stocks'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_stockexchange.User'),
        ),
    ]
